// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_little_genius = "CgkIl9L9_JIVEAIQBQ"; // <GPGSID>
        public const string leaderboard_highscores = "CgkIl9L9_JIVEAIQAw"; // <GPGSID>
        public const string achievement_grand_master_brain_break = "CgkIl9L9_JIVEAIQCQ"; // <GPGSID>
        public const string achievement_great_genius = "CgkIl9L9_JIVEAIQBg"; // <GPGSID>
        public const string achievement_2k_d = "CgkIl9L9_JIVEAIQCA"; // <GPGSID>
        public const string achievement_my_first_game = "CgkIl9L9_JIVEAIQAA"; // <GPGSID>
        public const string achievement_i_lost = "CgkIl9L9_JIVEAIQAg"; // <GPGSID>
        public const string achievement_love_the_brain_break = "CgkIl9L9_JIVEAIQCg"; // <GPGSID>

}

